from fastapi import FastAPI, UploadFile, File, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse, JSONResponse
import os
import uuid
import json
import asyncio
from typing import Dict, Any

from pipeline_runner import run_exofind_pipeline

app = FastAPI(title="ExoFind Dashboard API")

# Enable CORS for the Vite frontend
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

UPLOAD_DIR = os.path.join(os.path.dirname(__file__), "uploads")
os.makedirs(UPLOAD_DIR, exist_ok=True)

# In-memory store for pipeline results and progress streams
# In production, this would be Redis/PostgreSQL
job_results: Dict[str, Any] = {}
job_progress: Dict[str, list] = {}
job_status: Dict[str, str] = {} # 'running', 'completed', 'error'

@app.get("/api/health")
def health_check():
    return {"status": "ok", "service": "ExoFind Backend"}

@app.post("/api/upload")
async def upload_file(file: UploadFile = File(...)):
    """Uploads a FITS file and initializes a job."""
    if not file.filename.lower().endswith(('.fits', '.fits.gz', '.fit', '.fts')):
        raise HTTPException(status_code=400, detail="Only FITS files are supported")
        
    job_id = str(uuid.uuid4())
    file_path = os.path.join(UPLOAD_DIR, f"{job_id}_{file.filename}")
    
    import shutil
    with open(file_path, "wb") as buffer:
        shutil.copyfileobj(file.file, buffer)
        
    # Initialize job state
    job_progress[job_id] = []
    job_status[job_id] = "pending"
    
    return {"job_id": job_id, "filename": file.filename, "file_path": file_path}

@app.get("/api/run/{job_id}")
async def run_pipeline_sse(job_id: str, file_path: str):
    """
    Runs the pipeline and streams progress using Server-Sent Events (SSE).
    """
    if not os.path.exists(file_path):
        raise HTTPException(status_code=404, detail="File not found")

    async def event_generator():
        # Add to async event loop to not block FastAPI
        loop = asyncio.get_event_loop()
        
        # We need a queue to pass events from the synchronous pipeline thread to the async SSE generator
        queue = asyncio.Queue()
        
        def sync_progress_callback(progress_dict):
            # This is called from the worker thread
            asyncio.run_coroutine_threadsafe(queue.put(progress_dict), loop)
            
        def run_sync():
            try:
                job_status[job_id] = "running"
                result = run_exofind_pipeline(file_path, sync_progress_callback)
                job_results[job_id] = result
                job_status[job_id] = "completed"
                # Signal completion to the queue
                asyncio.run_coroutine_threadsafe(queue.put({"stage": "DONE"}), loop)
            except Exception as e:
                job_status[job_id] = "error"
                asyncio.run_coroutine_threadsafe(
                    queue.put({"stage": "ERROR", "message": str(e)}), loop
                )
        
        # Start the heavy pipeline in a separate thread
        task = loop.run_in_executor(None, run_sync)
        
        # Yield events from the queue as they arrive
        while True:
            event = await queue.get()
            
            if event["stage"] == "DONE":
                yield f"event: complete\ndata: {json.dumps({'job_id': job_id})}\n\n"
                break
            elif event["stage"] == "ERROR":
                yield f"event: error\ndata: {json.dumps(event)}\n\n"
                break
            else:
                # Store progress for late joiners (optional)
                if job_id in job_progress:
                    job_progress[job_id].append(event)
                yield f"event: progress\ndata: {json.dumps(event)}\n\n"
                
    return StreamingResponse(event_generator(), media_type="text/event-stream")

@app.get("/api/results/image")
def get_result_image():
    """Serves the latest exofind_bls_v2_results.png generated by the pipeline."""
    from fastapi.responses import FileResponse
    import os
    # Path to the exofind directory where the image is saved
    base_dir = os.path.dirname(os.path.abspath(__file__))
    image_path = os.path.abspath(os.path.join(base_dir, "..", "..", "exofind", "exofind_bls_v2_results.png"))
    
    if os.path.exists(image_path):
        return FileResponse(image_path)
    
    print(f"Image not found at expected path: {image_path}")
    raise HTTPException(status_code=404, detail=f"Image not found at {image_path}")

@app.get("/api/results/{job_id}")
def get_results(job_id: str):
    """Fetches the final results of a completed job."""
    if job_id not in job_status:
        raise HTTPException(status_code=404, detail="Job not found")
        
    if job_status[job_id] == "running":
        return JSONResponse(status_code=202, content={"status": "running"})
        
    if job_status[job_id] == "error":
        raise HTTPException(status_code=500, detail="Job failed during execution")
        
    if job_id in job_results:
        return job_results[job_id]
        
    raise HTTPException(status_code=404, detail="Results not found")


if __name__ == "__main__":
    import uvicorn
    uvicorn.run("server:app", host="0.0.0.0", port=8000, reload=True)
